### ISSUE TITLE
Migrate from GitLab CI to GitHub Actions

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/kwikipedia#11]
Now that GitHub has CI/CD built-in, there'd be less friction if we used it instead of the existing GitLab CI setup.

Replace the  [`.gitlab-ci.yml`](https://github.com/neelkamath/kwikipedia/blob/master/.gitlab-ci.yml) file with a `.github/workflows/workflow.yml` file. This workflow should trigger on pushes and pull requests.

**Comment by SuNNjek** [comment]
Hi, I'd like to take a look at this, could you assign me?
