### ISSUE TITLE
Can't download package on maven (Could not find com.neelkamath.kwikipedia:kwikipedia)

### ISSUE THREAD

**Issue by thibaud-sanchez** [neelkamath/kwikipedia#16]
I'm unable to get your dependency using gradle kotlin dsl 

```
Could not find com.neelkamath.kwikipedia:kwikipedia:.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

I've tried to define your repo into my build.gradle, no success
```
repositories {
    maven {
        url=uri("https://dl.bintray.com/neelkamath/kwikipedia")
    }
    mavenCentral()

}
```

I got a 403 if I try to download the jar from the maven page :  
https://mvnrepository.com/artifact/com.neelkamath.kwikipedia/kwikipedia/0.8.0

**Comment by neelkamath** [comment]
I pasted your `repositories` config into my `build.gradle.kts`:

```kotlin
plugins {
    application
    kotlin("jvm") version "1.4.31"
}

application.mainClassName = "AppKt"

repositories {
    mavenCentral()
    maven { url = uri("https://dl.bintray.com/neelkamath/kwikipedia") }
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("com.neelkamath.kwikipedia:kwikipedia:0.8.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3")
}
```

The application runs for me:

<img width="1440" alt="Screen Shot 2021-03-13 at 07 14 56" src="https://user-images.githubusercontent.com/24778804/111014863-d29c7200-83cb-11eb-843a-1fb1c74f973e.png">

You can try the following:
- When you were attempting to download the library, the package provider may have been experiencing downtime. Try again now.
- You may not have added the dependency (`implementation("com.neelkamath.kwikipedia:kwikipedia:0.8.0")`) to your `dependencies` block.
- Custom Maven URLs aren't working for you for some unknown reason. Try using `jcenter()` in your `repositories` block instead like:

  ```kotlin
  repositories {
      jcenter()
  }
  ```

**Comment by neelkamath** [comment]
I was previously hosting the package on Bintray but since Bintray is shutting down, I've migrated it to Jitpack today. The Bintray packages should still exist for another year (or however long Bintray is planning that for) but you can also use Jitpack (as documented in the README) from now on.

**Comment by neelkamath** [comment]
I'm closing this since I'm assumed it's working for you now. Reopen if it isn't.
