### ISSUE TITLE
Migrate from Kotest to kotlin.test

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/kwikipedia#9]
Initially, this project used the [`kotlin.test`](https://kotlinlang.org/api/latest/kotlin.test/) package for tests. Here's what the [`build.gradle.kts`](https://github.com/neelkamath/kwikipedia/blob/865fb98f39200b760f28be8c901eac11159cf89a/build.gradle.kts#L24) and [test cases](https://github.com/neelkamath/kwikipedia/blob/865fb98f39200b760f28be8c901eac11159cf89a/src/test/KWikipediaTest.kt) looked like at the time.

Later, we migrated to [Kotest](https://github.com/kotest/kotest), but there were [many issues](https://dev.to/neelkamath/why-i-migrated-from-kotest-to-junit-2k41) with it, so now we want to migrate back to `kotlin.test`.

Here's the steps you'll have to perform:
1. Replace Kotest with `kotlin.test` in `build.gradle.kts`. Note that the Kotest dependency is called [`io.kotlintest`](https://github.com/neelkamath/kwikipedia/blob/master/build.gradle.kts#L23) instead of _kotest_.
1. Edit the [test cases](https://github.com/neelkamath/kwikipedia/tree/master/src/test) to use `kotlin.test` instead of Kotest. You only need to update the function definition (e.g., the annotations); the actual test cases' function bodies will not be changed.

**Comment by SuNNjek** [comment]
Hey, I would like to do this, could you assign me?

**Comment by neelkamath** [comment]
@SuNNjek sorry! I just saw this now, and it seems like **CommanderTvis** forked this 2h ago, and just submitted a PR.

**Comment by neelkamath** [comment]
@SuNNjek let me know if you'd like me to create a new issue for migrating from [GitLab CI](https://github.com/neelkamath/kwikipedia/blob/master/.gitlab-ci.yml) to GitHub Actions.

**Comment by SuNNjek** [comment]
@neelkamath Yeah, guess I was too slow there, np :P Feel free to create the GitHub Actions issue, I can take a look at that

**Comment by neelkamath** [comment]
@SuNNjek  check #11
